# Generated by Django 5.1.5 on 2026-02-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_type', models.CharField(max_length=10)),
                ('score', models.FloatField()),
                ('confidence', models.FloatField()),
                ('verdict', models.CharField(max_length=200)),
                ('components', models.JSONField()),
                ('evidence', models.JSONField()),
                ('info', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fft_image', models.ImageField(blank=True, null=True, upload_to='visualizations/')),
                ('ela_image', models.ImageField(blank=True, null=True, upload_to='visualizations/')),
                ('noise_image', models.ImageField(blank=True, null=True, upload_to='visualizations/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
