# Generated by Django 5.2.11 on 2026-02-10 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_sitesettings_detection_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('fingerprint', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('detection_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Anonymous User',
                'verbose_name_plural': 'Anonymous Users',
                'ordering': ['-last_visit'],
            },
        ),
        migrations.AddField(
            model_name='detection',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detection',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detection',
            name='anonymous_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='detector.anonymoususer'),
        ),
    ]
