# Generated by Django 5.2.11 on 2026-02-11 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_anonymoususer_detection_share_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='use_anime_slugs',
        ),
    ]
